version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     
     steps:
       - checkout
       - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate&
            python manage.py runserver&
            echo "MASTER BRANCH!"
            
   build-prod:
     docker:
       - image: circleci/python:3.6.1
      
     steps:
       - checkout
       - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ansible virtualenv
            sudo apt-get update && sudo apt-get install jq
            ansible-playbook test.yml 
            
            echo "MASTER BRANCH!"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: test
      - build-prod:
          requires:
            - build
          filters:
            branches:
              only: test